export const ADD_TODO_CLICK = 'ADD_TODO_CLICK';
export const ADD_TODO_REQUEST = 'ADD_TODO_REQUEST';
export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
export const ADD_TODO_FAILED = 'ADD_TODO_FAILED';

export const REMOVE_TODO_CLICK = 'REMOVE_TODO_CLICK';
export const REMOVE_TODO_REQUEST = 'REMOVE_TODO_REQUEST';
export const REMOVE_TODO_SUCCESS = 'REMOVE_TODO_SUCCESS';
export const REMOVE_TODO_FAILED = 'REMOVE_TODO_FAILED';

export const UPDATE_TODO_CLICK = 'UPDATE_TODO_CLICK';
export const UPDATE_TODO_REQUEST = 'UPDATE_TODO_REQUEST';
export const UPDATE_TODO_SUCCESS = 'UPDATE_TODO_SUCCESS';
export const UPDATE_TODO_FAILED = 'UPDATE_TODO_FAILED';

export const MOVE_TODO = 'MOVE_TODO';

export const GET_TODO_INBOX = 'GET_TODO_INBOX';
export const GET_TODO_INBOX_SUCCESS = 'GET_TODO_INBOX_SUCCESS';
export const GET_TODO_TODAY = 'GET_TODO_TODAY';
export const GET_TODO_TODAY_SUCCESS = 'GET_TODO_TODAY_SUCCESS';
export const GET_TODO_WEEK = 'GET_TODO_WEEK';
export const GET_TODO_WEEK_SUCCESS = 'GET_TODO_WEEK_SUCCESS';

export const GET_PROJECT = 'GET_PROJECT';
export const GET_PROJECT_SUCCESS = 'GET_PROJECT_SUCCESS';
export const ADD_PROJECT = 'ADD_PROJECT';
export const ADD_PROJECT_SUCCESS = 'ADD_PROJECT_SUCCESS';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS';
